stages:
  - publish

# Publish Template
publish:
  rules:
    - if: $CI_COMMIT_TAG
  variables:
    GIT_STRATEGY: clone
    GIT_SUBMODULE_STRATEGY: recursive
  stage: publish
  script:
    - export GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_REGISTRY_CREDENTIAL_JSON
    - ./buildSrc/scripts/publish.sh $CI_COMMIT_TAG
  tags:
    - android
