object BuildDependenciesVersions {
    const val GRADLE = "7.0.2"
    const val KOTLIN = "1.5.31"
    const val COROUTINES = "1.5.1-native-mt"
    const val CORE_KTX = "1.2.0"
    const val APPCOMPAT = "1.3.1"
    const val FRAGMENT = "1.4.0"
    const val NAVIGATION = "2.4.0"
    const val GOOGLE_ARTIFACTS_REGISTRY = "2.1.1"
    const val CONSTRAIN_LAYOUT = "2.1.0"
    const val REYCLERVIEW = "1.1.0"
    const val MATERIAL_COMPONENTS = "1.2.0"
    const val FLEX_BOX = "3.0.0"
    const val SPINNER_DATE_PICKER = "2.0.1"
    const val SHIMMER_FRAME_LAYOUT = "0.5.0"
    const val MULTIDEX = "2.0.1"
    const val LIFECYCLE = "2.4.0"
    const val RETROFIT = "2.6.4"
    const val OKHTTP = "4.7.2"
    const val GSON = "2.8.9"
    const val ROOM = "2.3.0"
    const val TIMBER = "4.7.1"
    const val DAGGER = "2.34"
    const val WORK_MANAGER = "2.7.1"
    const val RECYCLER_VIEW = "1.1.0"
    const val HILT = "2.38.1"
    const val HILT_COMPILER = "1.0.0"

    const val ZXING = "3.4.0"
    const val ZXING_ANDROID = "3.3.0"
    const val SWIPE_REFRESH = "1.0.0"
    const val KOTLIN_POET = "1.2.0"
    const val PAGING = "2.1.1"
    const val PAGING_3 = "3.0.0"
    const val GLIDE = "4.11.0"
    const val CARDVIEW = "1.0.0"
    const val KODEIN_DI = "7.4.0"
    const val FIREBASE_DATABASE = "19.6.0"
    const val FIREBASE_MESSAGING = "21.0.0"
    const val FIREBASE_AUTH = "20.0.1"
    const val FIREBASE_ANALYTIC = "18.0.0"
    const val FIREBASE_CRASHLYTIC = "17.3.0"
    const val FIREBASE_CRASHLYTIC_GRADLE = "2.4.1"
    const val FIREBASE_REMOTE_CONFIG = "20.0.1"
    const val FIREBASE_FIRESTORE = "22.0.0"
    const val FIREBASE_PERF = "19.0.10"
    const val FIREBASE_PERF_PLUGIN = "1.3.1"
    const val FIREBASE_DYNAMIC_LINK = "19.1.0"
    const val FIREBASE_BOM = "28.4.2"
    const val GOOGLE_PLAY_SERVICES = "17.0.0"
    const val EPOXY = "4.5.0"
    const val EXOPLAYER = "2.15.1"
    const val FABRIC = "1.31.2"
    const val GRGIT = "4.1.1"
    const val GOOGLE_SERVICES = "4.3.3"
    const val COROUTINE_PLAY_SERVICE = "1.3.6"
    const val CAMERA_VIEW = "2.7.1"
    const val CAMERAX_CAMERA2 = "1.0.1"
    const val CAMERAX_CORE = "1.0.1"
    const val CAMERAX_LIFECYCLE = "1.0.1"
    const val CAMERAX_VIEW = "1.0.0-alpha27"
    const val IMAGE_PICKER_VIEW = "2.4.0"
    const val MLKIT = "24.0.1"
    const val MLKIT_BARCODE_MODEL = "16.0.1"
    const val GOOGLE_BARCODE_SCANNING = "17.0.0"
    const val GOOGLE_BARCODE_MODEL = "16.1.4"
    const val SUNMI_PRINTER = "1.0.13"
    const val MP_CHART = "3.1.0"
    const val MAP_STRUCT = "1.3.1.Final"
    const val MAP_STRUCT_KOTLIN_BUILDER = "1.3.1.2"
    const val PLAY_CORE = "1.8.0"
    const val PLAY_CORE_KTX = "1.8.1"
    const val PROTOBUF = "3.11.1"
    const val DESUGAR_JDK_LIBS = "1.1.5"
    const val SHORTCUT_BADGE = "1.1.22@aar"
    const val TRIPI_FLIGHT_DEV = "0.4.0-dev"
    const val TRIPI_FLIGHT_PROD = "0.4.0"
    const val TRIPI_HOTEL_DEV = "0.4.0-dev"
    const val TRIPI_HOTEL_PROD = "0.4.0"
    const val TRIPI_PREPAID_DEV = "0.4.0-dev"
    const val TRIPI_PREPAID_PROD = "0.4.0"

    // React Native
    const val JSC_FLAVOR = "+"

    // Debug
    const val LEAK_CANARY = "2.8.1"
    const val DEBUG_DB = "v1.0.6"

    // Tests
    const val JUNIT = "4.12"
    const val JUNIT_EXT = "1.1.0"
    const val MOCKITO = "3.0.0"

    const val EXT = "1.1.0"
    const val ESPRESSO = "3.2.0"
    const val ARCH_TESTING = "2.1.0"
    const val ROBOLECTRIC = "4.4"
    const val ORCHESTRATOR = "1.1.0"
    const val EXT_TRUTH = "1.1.0"
    const val TEST_RULE = "1.1.1"

    const val PHOTO_VIEW = "2.3.0"

    const val AUTO_SERVICE = "1.0-rc4"

    const val PLAY_SERVICES_AUTH = "17.0.0"
    const val FACEBOOK_AUTH = "5.13.0"
    const val REACT_NATIVE = "+"
    const val REACT_NATIVE_0_61_PLUS = "[0.61.0,)"

    // Teko
    const val AUTH = "0.4.+"
    const val CORE = "0.2.+"
    const val PAYMENT = "0.7.2"
    const val PAYMENT_PROD = "0.7.2-prod"
    const val TRACKER = "0.2.+"
    const val TERRA = "0.6.+"
    const val HESTIA = "0.0.+"
    const val APOLLO = "1.4.+"
    const val VNSHOP = "1.3.+"
    const val FOOTPRINT_DTO = "0.33.9-lite"
    const val DISCOVERY = "0.0.1"
    const val ORDER = "0.0.2"
    const val CART = "0.38.0"
    const val LOYALTY = "0.1.0-alpha9"
    const val IRIS = "0.1.0-alpha1"
    const val JIRA_TEST_JUNIT4 = "1.1.2"

    const val SERVICE_PPM = "0.3.+"
    const val SERVICE_POLICY = "0.3.+"
    const val SERVICE_DISCOVERY = "0.3.+"
    const val SERVICE_USER = "0.3.+"
    const val SERVICE_DCA = "0.3.+"
    const val SERVICE_LOCATION = "0.3.+"
    const val SERVICE_ORDER = "0.3.+"
    const val SERVICE_NOTIFICATION = "0.3.+"
    const val SERVICE_ID_ADMIN = "0.3.+"
    const val SERVICE_WMS = "0.3.+"
    const val SERVICE_SELLER = "0.3.+"
    const val SERVICE_PVIS = "0.3.+"
    const val SERVICE_SEARCH = "0.3.+"
    const val SERVICE_FINANCE = "0.3.+"
    const val SERVICE_TICKET = "0.3.+"
    const val SERVICE_POS = "0.3.+"
    const val SERVICE_CATALOG = "0.3.+"
    const val SERVICE_CART = "0.3.+"
    const val SERVICE_BANK = "0.0.+"
    const val SERVICE_COV = "0.0.+"
    const val SERVICE_FLAGSUP = "0.0.+"
    const val SERVICE_APPROVAL = "0.0.+"

    const val TEKO_AUTH_CORE = "1.+"
    const val TEKO_AUTH_LOGIN_UI = "1.+"
    const val TEKO_AUTH_LOGIN_CORE_UI = "0.+"
    const val TERRA_AUTH = "0.+"
    const val TERRA_AUTH_GOOGLE_LOGIN = "0.+"
    const val TERRA_AUTH_FACEBOOK_LOGIN = "0.+"
    const val TERRA_AUTH_KIT = "0.+"
    const val TERRA_AUTH_JS_BRIDGE = "0.+"

    const val TEKO_AF_DATA = "0.+"
    const val TEKO_AF_LOGGING = "0.+"
    const val TEKO_AF_UI = "0.+"
    const val TEKO_AF_UTIL = "0.+"
    const val TEKO_AF_UTIL_ANDROID = "0.+"
    const val TEKO_AF_SKELETON = "0.+"
    const val TEKO_AF_BARCODE_UTIL = "0.+"
    const val TEKO_AF_SERVICE = "0.+"
    const val TEKO_AF_NOTIFICATION = "0.+"
    const val TEKO_AF_PROCESSOR = "0.+"
    const val TEKO_AF_ANNOTATION = "0.+"
    const val TEKO_AF_MESSAGING = "0.+"
    const val TEKO_AF_FRAMEWORK = "0.+"
    const val TEKO_AF_MEDIAVIEWER = "0.+"
    const val TEKO_AF_TESTUTIL = "0.+"
    const val TEKO_AF_TESTUTIL_ANDROID = "0.+"

    const val TEKO_PAYMENT_CORE_V2 = "1.+"
    const val TEKO_PAYMENT_UI = "1.+"
    const val TEKO_PAYMENT_KIT = "1.+"
    const val TEKO_PAYMENT_OBSERVER_FIREBASE_V2 = "1.+"
    const val TEKO_PAYMENT_MANAGER_V2 = "1.+"
    const val TEKO_PAYMENT_REACT_NATIVE_BRIDGE = "1.+"

    const val TEKO_TRACKER_CORE = "2.+"
    const val TEKO_TRACKER_EVENT = "2.+"
    const val TEKO_TRACKER_UTIL = "2.+"
    const val TEKO_TRACKER_MANAGER = "2.+"

    const val TERRA_CORE = "0.+"
    const val TERRA_CORE_ANDROID = "0.+"
    const val TERRA_JS_BRIDGE = "0.+"
    const val TERRA_JS_BRIDGE_CORE = "0.+"
    const val TERRA_REACT_NATIVE_BRIDGE = "0.+"

    const val HESTIA_CORE = "1.+"
    const val HESTIA_ANDROID = "1.+"
    const val TERRA_HESTIA = "1.+"
    const val HESTIA_ANDROID_WEBAPP = "1.+"
    const val HESTIA_ANDROID_NATIVE = "1.+"
    const val HESTIA_ANDROID_REACT_NATIVE = "1.+"
    const val HESTIA_ANDROID_REACT_NATIVE_UI_FRAGMENT = "1.+"
    const val HESTIA_ANDROID_REACT_NATIVE_UI_ACTIVITY = "1.+"
    const val HESTIA_WEBVIEW = "0.+"
    const val HESTIA_KIT_CONNECTOR = "1.+"

    const val TEKO_APOLLO = "1.+"
    const val TERRA_APOLLO = "1.+"

    const val TEKO_LOYALTY_CORE = "1.+"
    const val TEKO_LOYALTY_MODEL = "1.+"
    const val TEKO_LOYALTY_TERRA = "1.+"
    const val TEKO_LOYALTY_CONSUMER_TERRA = "1.+"
    const val TEKO_LOYALTY_CONSUMER_UI = "1.+"
    const val TEKO_LOYALTY_COMPONENT = "1.+"
    const val TEKO_LOYALTY_STAFF_TERRA = "1.+"
    const val TEKO_LOYALTY_STAFF_UI = "1.+"
    const val TEKO_LOYALTY_KIT = "1.+"

    const val TEKO_IRIS_CORE = "0.+"
    const val TERRA_IRIS = "0.+"
    const val TEKO_VNPAY_BILLING = "1.0.0-alpha1"

    const val TEKO_NOTIFICATION_CORE = "0.+"
    const val TEKO_TERRA_NOTIFICATION = "0.+"
    const val TEKO_NOTIFICATION_UI = "0.+"
    const val TEKO_NOTIFICATION_UTIL = "0.+"
    const val TEKO_NOTIFICATION_UTIL_ANNOTATION = "0.+"
    const val TEKO_NOTIFICATION_UTIL_PROCESSOR = "0.+"
    const val TEKO_NOTIFICATION_FCM_UTIL = "0.+"
    const val TEKO_NOTIFICATION_FCM_UTIL_ANNOTATION = "0.+"
    const val TEKO_NOTIFICATION_FCM_UTIL_PROCESSOR = "0.+"

    const val HESTIA_ORDER_CORE = "0.0.1"
    const val TERRA_HESTIA_ORDER = "0.0.1"
    const val HESTIA_ORDER_UI = "0.0.1"
    const val TERRA_HESTIA_ORDER_UI = "0.0.1"
    const val TERRA_LINK_PROCESSOR = "0.0.1-alpha.1-SNAPSHOT"
}

