import dependencies.TekoArtifacts

object TekoDependenciesVersions : HashMap<String, String>() {
    init {
        this[TekoArtifacts.TEKO_AF_DATA] = "1.+"
        this[TekoArtifacts.TEKO_AF_LOGGING] = "1.+"
        this[TekoArtifacts.TEKO_AF_UI] = "1.+"
        this[TekoArtifacts.TEKO_AF_UTIL] = "1.+"
        this[TekoArtifacts.TEKO_AF_UTIL_ANDROID] = "1.+"
        this[TekoArtifacts.TEKO_AF_SKELETON] = "1.+"
        this[TekoArtifacts.TEKO_AF_BARCODE_UTIL] = "0.+"
        this[TekoArtifacts.TEKO_AF_SERVICE] = "1.+"
        this[TekoArtifacts.TEKO_AF_NOTIFICATION] = "1.+"
        this[TekoArtifacts.TEKO_AF_PROCESSOR] = "1.+"
        this[TekoArtifacts.TEKO_AF_ANNOTATION] = "1.+"
        this[TekoArtifacts.TEKO_AF_MESSAGING] = "1.+"
        this[TekoArtifacts.TEKO_AF_FRAMEWORK] = "1.+"
        this[TekoArtifacts.TEKO_AF_MEDIAVIEWER] = "1.+"
        this[TekoArtifacts.TEKO_AF_TESTUTIL] = "1.+"
        this[TekoArtifacts.TEKO_AF_TESTUTIL_ANDROID] = "1.+"
        this[TekoArtifacts.TEKO_AF_QR_GENERATOR] = "0.+"

        this[TekoArtifacts.TERRA_CORE] = "0.+"
        this[TekoArtifacts.TERRA_CORE_ANDROID] = "1.+"
        this[TekoArtifacts.TERRA_BUS_EXTENSION] = "0.+"
        this[TekoArtifacts.TERRA_JS_BRIDGE] = "1.+"
        this[TekoArtifacts.TERRA_JS_BRIDGE_CORE] = "0.+"
        this[TekoArtifacts.TERRA_REACT_NATIVE_BRIDGE] = "0.+"

        this[TekoArtifacts.TEKO_AUTH_CORE] = "1.+"
        this[TekoArtifacts.TEKO_AUTH_LOGIN_UI] = "1.+"
        this[TekoArtifacts.TERRA_AUTH] = "1.+"
        this[TekoArtifacts.TERRA_AUTH_GOOGLE_LOGIN] = "1.+"
        this[TekoArtifacts.TERRA_AUTH_FACEBOOK_LOGIN] = "1.+"
        this[TekoArtifacts.TERRA_AUTH_KIT] = "1.+"
        this[TekoArtifacts.TERRA_AUTH_JS_BRIDGE] = "1.+"

        this[TekoArtifacts.TEKO_TRACKER_CORE] = "2.+"
        this[TekoArtifacts.TEKO_TRACKER_EVENT] = "2.+"
        this[TekoArtifacts.TEKO_TRACKER_UTIL] = "2.+"
        this[TekoArtifacts.TEKO_TRACKER_MANAGER] = "2.+"

        this[TekoArtifacts.TEKO_PAYMENT_CORE_V2] = "1.+"
        this[TekoArtifacts.TEKO_PAYMENT_UI] = "1.+"
        this[TekoArtifacts.TEKO_PAYMENT_KIT] = "1.+"
        this[TekoArtifacts.TEKO_PAYMENT_OBSERVER_FIREBASE_V2] = "1.+"
        this[TekoArtifacts.TEKO_PAYMENT_MANAGER_V2] = "1.+"
        this[TekoArtifacts.TEKO_PAYMENT_REACT_NATIVE_BRIDGE] = "1.+"
        this[TekoArtifacts.TEKO_PAYMENT_CONTROLLER_UI] = "1.+"
        this[TekoArtifacts.TEKO_PAYMENT_SELECT_METHODS_UI] = "0.+"

        this[TekoArtifacts.TEKO_APOLLO] = "1.+"
        this[TekoArtifacts.TERRA_APOLLO] = "1.+"

        this[TekoArtifacts.TEKO_LOYALTY_CORE] = "1.+"
        this[TekoArtifacts.TEKO_LOYALTY_MODEL] = "1.+"
        this[TekoArtifacts.TEKO_LOYALTY_TERRA] = "1.+"
        this[TekoArtifacts.TEKO_LOYALTY_CONSUMER_TERRA] = "1.+"
        this[TekoArtifacts.TEKO_LOYALTY_CONSUMER_UI] = "1.+"
        this[TekoArtifacts.TEKO_LOYALTY_COMPONENT] = "1.+"
        this[TekoArtifacts.TEKO_LOYALTY_STAFF_TERRA] = "1.+"
        this[TekoArtifacts.TEKO_LOYALTY_STAFF_UI] = "1.+"
        this[TekoArtifacts.TEKO_LOYALTY_KIT] = "1.+"
        this[TekoArtifacts.TEKO_LOYALTY_TRACKING] = "1.+"

        this[TekoArtifacts.IRIS_CORE] = "0.+"
        this[TekoArtifacts.TERRA_IRIS] = "0.+"

        this[TekoArtifacts.HESTIA_CORE] = "1.+"
        this[TekoArtifacts.HESTIA_ANDROID] = "1.+"
        this[TekoArtifacts.TERRA_HESTIA] = "1.+"
        this[TekoArtifacts.HESTIA_ANDROID_WEBAPP] = "1.+"
        this[TekoArtifacts.HESTIA_ANDROID_NATIVE] = "1.+"
        this[TekoArtifacts.HESTIA_ANDROID_REACT_NATIVE] = "1.+"
        this[TekoArtifacts.HESTIA_ANDROID_REACT_NATIVE_UI_FRAGMENT] = "1.+"
        this[TekoArtifacts.HESTIA_ANDROID_REACT_NATIVE_UI_ACTIVITY] = "1.+"
        this[TekoArtifacts.HESTIA_WEBVIEW] = "1.+"
        this[TekoArtifacts.HESTIA_KIT_CONNECTOR] = "1.+"
        this[TekoArtifacts.HESTIA_TRACKING_BRIDGE] = "1.+"
        this[TekoArtifacts.HESTIA_AUTH_CONTROLLER] = "0.+"
        this[TekoArtifacts.HESTIA_PAYMENT_CONTROLLER] = "0.+"

        this[TekoArtifacts.HESTIA_ORDER_CORE] = "0.+"
        this[TekoArtifacts.TERRA_HESTIA_ORDER] = "0.+"
        this[TekoArtifacts.HESTIA_ORDER_UI] = "0.+"
        this[TekoArtifacts.TERRA_HESTIA_ORDER_UI] = "0.+"
        this[TekoArtifacts.TEKO_NOTIFICATION_CORE] = "0.+"
        this[TekoArtifacts.TEKO_NOTIFICATION_UI] = "0.+"
        this[TekoArtifacts.TEKO_TERRA_NOTIFICATION] = "0.+"
        this[TekoArtifacts.TEKO_NOTIFICATION_FCM_UTIL] = "0.+"
    }
}

