package utils

const val USE_PREBUILT_LIBRARIES = "usePrebuiltLibraries"
const val USE_SOME_LOCAL_LIBRARIES = "useSomeLocalLibraries"
const val APPLICATION_ID = "applicationId"
const val DPOS_APPLICATION_ID = "dposApplicationId"
const val SELF_KIOSK_APPLICATION_ID = "selfkioskApplicationId"
const val GROUP = "group"
const val VERSION_NAME = "versionName"
const val VERSION_CODE = "versionCode"
const val TEST_INSTRUMENTATION_RUNNER = "testInstrumentationRunner"
const val COMPILE_SDK_VERSION = "compileSdkVersion"
const val BUILD_TOOLS_VERSION = "buildToolsVersion"
const val MIN_SDK_VERSION = "minSdkVersion"
const val TARGET_SDK_VERSION = "targetSdkVersion"
const val MULTIDEX_ENABLED = "multiDex"
const val SUPPORT_VECTOR_DRAWABLE = "supportVectorDrawable"
const val IS_MINIFY_RELEASE = "isMinifyRelease"
const val REPO_TYPE = "repoType"
const val REPO_NAME = "repoName"
const val PUBLISH_EXCLUSIONS = "publishExclusions"